<template>
  <v-navigation-drawer>
    <v-list>
      <v-list-item>
        <v-btn
          prepend-icon="mdi-logout"
          variant="outlined"
          color="red-lighten-3"
          block
        >
          Logout
        </v-btn></v-list-item
      >
    </v-list>
    <v-divider></v-divider>

    <v-list density="compact" nav>
      <v-list-item
        prepend-icon="mdi-home"
        title="Home"
        value="Home"
        :to="'/'"
      ></v-list-item>
      <v-list-item
        prepend-icon="mdi-menu"
        title="Quizzes"
        value="quizzes"
        :to="'/quizzes'"
      ></v-list-item>
      <v-list-item
        prepend-icon="mdi-play"
        title="Run"
        value="run"
        :to="'/run'"
      ></v-list-item>
    </v-list>
  </v-navigation-drawer>
</template>
